name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cpp-linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup APT dependencies
        run: |
          wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && \
          sudo add-apt-repository 'deb ${{ env.LLVM_REPO }} ${{ env.LLVM_REPO_TOOLCHAIN }} main' &&
          sudo add-apt-repository 'deb-src ${{ env.LLVM_REPO }} ${{ env.LLVM_REPO_TOOLCHAIN }} main' && \
          sudo apt-get update && \
          sudo apt-get install -y gcc-${{ env.GCC_VERSION }} llvm-${LLVM_VERSION} clang-${LLVM_VERSION}
        env:
          GCC_VERSION: 12
          LLVM_VERSION: 16
          LLVM_REPO: http://apt.llvm.org/jammy/
          LLVM_REPO_TOOLCHAIN: llvm-toolchain-jammy-16

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          # Only update a single comment in PR threads
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
        # When stable for deployment,
        # run: exit 1